#!/usr/bin/env bash
# Regenerate the web assets in docs/assets/ from the source art in assets/.
#
# Source PNGs are 1024x1024 (portraits) and ~1200px wide (backgrounds).
# This downscales them to 512px / 1000px WebP, bringing the total payload
# under ~1.5 MB. Painted portraits that exist in docs/assets/portraits/*.webp
# without a corresponding PNG in assets/ are left untouched.
#
# Procedural SVG avatars are regenerated by scripts/generate-avatars.js each
# run; they already run ~3 KB each.
#
# Requires: ImageMagick (`convert`).
# Usage: ./scripts/optimize-assets.sh

set -euo pipefail

cd "$(cd "$(dirname "$0")" && pwd)/.."

if ! command -v convert &>/dev/null; then
  echo "ERROR: ImageMagick 'convert' not found." >&2
  echo "  Debian/Ubuntu: sudo apt install imagemagick" >&2
  echo "  macOS:         brew install imagemagick" >&2
  exit 1
fi

PORTRAIT_SIZE=512
BACKGROUND_WIDTH=1000
PORTRAIT_QUALITY=82
BACKGROUND_QUALITY=80

mkdir -p docs/assets/portraits docs/assets/backgrounds

echo "Converting portrait PNGs -> ${PORTRAIT_SIZE}px WebP…"
shopt -s nullglob
for f in assets/portraits/*.png; do
  name=$(basename "$f" .png)
  convert "$f" -resize "${PORTRAIT_SIZE}x${PORTRAIT_SIZE}" \
    -quality "$PORTRAIT_QUALITY" -define webp:method=6 \
    "docs/assets/portraits/${name}.webp"
  printf '  %-12s %s\n' "$name" "$(du -h "docs/assets/portraits/${name}.webp" | cut -f1)"
done

echo "Converting backgrounds -> ${BACKGROUND_WIDTH}px WebP…"
for f in assets/backgrounds/*.png; do
  name=$(basename "$f" .png)
  convert "$f" -resize "${BACKGROUND_WIDTH}x>" \
    -quality "$BACKGROUND_QUALITY" -define webp:method=6 \
    "docs/assets/backgrounds/${name}.webp"
  printf '  %-12s %s\n' "$name" "$(du -h "docs/assets/backgrounds/${name}.webp" | cut -f1)"
done

echo "Regenerating procedural avatars…"
node scripts/generate-avatars.js

echo "Copying SVG portraits/backgrounds verbatim…"
cp -f assets/portraits/*.svg docs/assets/portraits/ 2>/dev/null || true
cp -f assets/backgrounds/*.svg docs/assets/backgrounds/ 2>/dev/null || true

# Drop any web asset whose source no longer exists.
for f in docs/assets/portraits/*; do
  [ -e "$f" ] || continue
  base=$(basename "$f"); stem="${base%.*}"
  if [ ! -e "assets/portraits/${stem}.png" ] \
     && [ ! -e "assets/portraits/${stem}.svg" ] \
     && [ ! -e "assets/portraits/${stem}.webp" ]; then
    echo "  removing orphan ${base}"
    rm -f "$f"
  fi
done
for f in docs/assets/backgrounds/*; do
  [ -e "$f" ] || continue
  base=$(basename "$f"); stem="${base%.*}"
  if [ ! -e "assets/backgrounds/${stem}.png" ] \
     && [ ! -e "assets/backgrounds/${stem}.svg" ] \
     && [ ! -e "assets/backgrounds/${stem}.webp" ]; then
    echo "  removing orphan ${base}"
    rm -f "$f"
  fi
done

echo
echo "Source art:  $(du -sh assets | cut -f1)"
echo "Web payload: $(du -sh docs/assets | cut -f1)"
echo
echo "Done. Verify with: npm run check"
